import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - KIMS",
  description:
    "How KIMS collects, uses, and protects account, library, playback, and analytics data.",
};

const sections = [
  {
    title: "Information We Collect",
    body: [
      "When you create an account, KIMS stores your name, email address, password hash, account role, and account timestamps.",
      "When you use the library, KIMS stores your favorites, playlists, playlist tracks, playback history, play counts, and recent listening timestamps.",
      "When you request a password reset, KIMS stores temporary reset data such as OTP hashes, expiry times, and whether a reset code has been used.",
    ],
  },
  {
    title: "How We Use Information",
    body: [
      "We use account data to authenticate you, keep your library attached to your account, and protect admin-only content management tools.",
      "We use favorites, playlists, and playback history to power your saved library, history page, play counts, and personalized recommendations.",
      "We use reset-password data only to verify password reset requests and reduce account abuse.",
    ],
  },
  {
    title: "Analytics And Monitoring",
    body: [
      "KIMS may use privacy-conscious analytics to understand product usage, page activity, and feature performance.",
      "KIMS may use error monitoring to diagnose crashes, API failures, and performance issues. Error reports can include technical details such as browser, route, environment, and stack traces.",
    ],
  },
  {
    title: "Storage And Media",
    body: [
      "Track metadata is stored in the KIMS database. Cover images and audio files can be stored in Supabase Storage buckets.",
      "Public cover images may be delivered through public storage URLs. Private audio files may be delivered through temporary signed URLs generated by the backend.",
    ],
  },
  {
    title: "Sharing",
    body: [
      "KIMS does not sell your personal information.",
      "KIMS uses service providers such as hosting, database, storage, analytics, monitoring, and email delivery providers to operate the app.",
      "We may disclose information if required to comply with legal obligations or to protect the service from abuse.",
    ],
  },
  {
    title: "Security",
    body: [
      "Passwords are stored as password hashes, not plain text.",
      "Protected API routes require authentication, and admin tools require an admin role.",
      "No internet service can be guaranteed perfectly secure, but KIMS uses practical safeguards to reduce unauthorized access and abuse.",
    ],
  },
  {
    title: "Your Choices",
    body: [
      "You can remove favorites, delete playlist items, clear history, and update your password through the app flows available today.",
      "For account deletion or privacy requests that are not yet self-service in the app, contact the KIMS maintainer using the project contact channel.",
    ],
  },
  {
    title: "Changes",
    body: [
      "KIMS may update this policy as the product changes. The latest version will be posted on this page with an updated date.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[var(--color-background)] px-4 py-10 text-[var(--color-text-primary)] md:px-6">
      <article className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="text-sm font-semibold text-[var(--color-accent-primary)] transition-colors hover:text-[color-mix(in_srgb,var(--color-accent-primary)_82%,var(--color-text-primary))] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent-primary)]"
        >
          Back to KIMS
        </Link>

        <header className="mt-8 border-b border-[var(--color-border)] pb-6">
          <p className="text-sm font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
            Legal
          </p>
          <h1 className="mt-2 text-3xl font-bold text-[var(--color-text-primary)]">
            Privacy Policy
          </h1>
          <p className="mt-3 text-sm leading-6 text-[var(--color-text-muted)]">
            Last updated: June 29, 2026
          </p>
        </header>

        <div className="space-y-8 py-8">
          <section>
            <p className="text-base leading-7 text-[var(--color-text-muted)]">
              KIMS, Kim&apos;s Music Station, is a free music and sound library
              for creators. This policy explains what data KIMS collects, why it
              is used, and how it supports account, library, playback, and admin
              features.
            </p>
          </section>

          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-xl font-bold text-[var(--color-text-primary)]">
                {section.title}
              </h2>
              <div className="mt-3 space-y-3">
                {section.body.map((paragraph) => (
                  <p
                    key={paragraph}
                    className="text-sm leading-6 text-[var(--color-text-muted)]"
                  >
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </article>
    </main>
  );
}
