migrate-up:
	go run ./cmd/migrate -direction=up

migrate-down:
	go run ./cmd/migrate -direction=down

migrate-steps-up:
	go run ./cmd/migrate -direction=up -steps=1

migrate-steps-down:
	go run ./cmd/migrate -direction=down -steps=1
